# Generated by Django 5.0.1 on 2024-01-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lenguaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre Lenguaje')),
            ],
        ),
        migrations.CreateModel(
            name='SistemaOperativo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre SO')),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('apellido_paterno', models.CharField(max_length=100, verbose_name='Apellido Paterno')),
                ('apellido_materno', models.CharField(max_length=100, verbose_name='Apellido Materno')),
                ('foto', models.ImageField(upload_to='imagenes/', verbose_name='Foto')),
                ('lenguaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.lenguaje', verbose_name='Lenguaje')),
                ('sistema_operativo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.sistemaoperativo', verbose_name='Sistema Operativo')),
            ],
        ),
    ]
