# Generated by Django 5.0.1 on 2024-01-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40, verbose_name='nombre')),
                ('apellido_paterno', models.CharField(max_length=40, verbose_name='apellido_paterno')),
                ('apellido_materno', models.CharField(max_length=40, verbose_name='apellido_materno')),
                ('direccion', models.TextField(null=True, verbose_name='direccion')),
                ('creditos', models.CharField(max_length=40, verbose_name='creditos')),
                ('foto', models.ImageField(null=True, upload_to='imagenes/', verbose_name='imagen')),
            ],
        ),
    ]
