# Generated by Django 5.0.1 on 2024-01-08 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='apellido_materno',
            field=models.CharField(max_length=40, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='apellido_paterno',
            field=models.CharField(max_length=40, verbose_name='Apellido Paterno'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='creditos',
            field=models.CharField(max_length=40, verbose_name='Créditos'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='direccion',
            field=models.TextField(null=True, verbose_name='Dirección'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='foto',
            field=models.ImageField(null=True, upload_to='imagenes/', verbose_name='Foto'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nombre',
            field=models.CharField(max_length=40, verbose_name='Nombre'),
        ),
    ]
