# Generated by Django 5.0.1 on 2024-01-16 00:56

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('last_name_1', models.CharField(max_length=50, verbose_name='Last name 1')),
                ('last_name_2', models.CharField(max_length=50, verbose_name='Last name 2')),
                ('img', models.ImageField(blank=True, null=True, upload_to='imagenes/', verbose_name='Image')),
                ('education', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Derecho', 'Derecho'), ('Contabilidad', 'Contabilidad'), ('Administración', 'Administración')], max_length=50, verbose_name='Education')),
                ('degree', models.CharField(choices=[('Sistemas', 'Sistemas'), ('Derecho', 'Derecho'), ('Contabilidad', 'Contabilidad'), ('Administración', 'Administración')], max_length=50, verbose_name='Degree')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.area', verbose_name='Area')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='EducationLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=True, verbose_name='Status')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Created')),
                ('updated_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Level Education')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
