# Generated by Django 5.0.1 on 2024-01-16 01:09

from django.db import migrations
import os
from crud5.setting import BASE_DIR

def make_migration():
    return open(os.path.join(BASE_DIR, 'migrations/data.sql'), 'r').read()


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(make_migration(),)
    ]
